# ASP.NET
# Build and test ASP.NET projects.
# Add steps that publish symbols, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/aspnet/build-aspnet-4

trigger:
- main

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  solutionPath: "src/ShoppingLists.sln"

stages:
  - stage: Build
    displayName: Build
    jobs:
  #     - job: "BuildApi"
  #       steps:
  #         - task: DotNetCoreCLI@2
  #           displayName: dotnet Publish
  #           inputs:
  #             command: publish
  #             publishWebProjects: false
  #             projects: "$(solutionPath)"
  #             arguments: "--configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)"
  #             zipAfterPublish: false
  #         - task: ArchiveFiles@2
  #           displayName: Zip Api
  #           inputs:
  #             rootFolderOrFile: "$(Build.ArtifactStagingDirectory)/src"
  #             includeRootFolder: false
  #             archiveType: "zip"
  #             archiveFile: "$(Build.ArtifactStagingDirectory)/out/shoppinglists-api-$(Build.BuildId).zip"
  #             replaceExistingArchive: true
  #         - task: PublishBuildArtifacts@1
  #           displayName: "Publish Artifact (API)"
  #           inputs:
  #             PathtoPublish: "$(Build.ArtifactStagingDirectory)/out"
  #             ArtifactName: "drop_api"
  #             publishLocation: "Container"

      - deployment: Deploy
        environment: my-food-tracker-dev
        #dependsOn: BuildApi
        strategy:
          runOnce:
            deploy:
              steps:
              # https://learn.microsoft.com/en-us/azure/devops/pipelines/tasks/reference/download-build-artifacts-v1?view=azure-pipelines
              - task: DownloadBuildArtifacts@1
                inputs:
                  project: 'JMSL'
                  pipeline: 'johnmmoss.shoppinglists'
                  buildType: specific
                  buildVersionToDownload: specific
                  buildId: 406
                  artifactName: drop_api
                  downloadPath: "$(Pipeline.Workspace)"

              - task: AzureRmWebAppDeployment@4
                displayName: DeployApi
                inputs:
                  ConnectionType: "AzureRM"
                  azureSubscription: "myfoodtracker-azure-devops"
                  appType: "apiApp"
                  WebAppName: "unstacked"
                  packageForLinux: "$(Pipeline.Workspace)/**/*.zip"

                # - task: AzureCLI@2
                #   displayName: "Create Infra"
                #   inputs:
                #     scriptType: pscore
                #     scriptLocation: inlineScript
                #     addSpnToEnvironment: true
                #     azureSubscription: $(azure_devops_subscription_name)
                #     inlineScript: |
                #       $env:ARM_CLIENT_ID=$env:servicePrincipalId
                #       $env:ARM_CLIENT_SECRET=$env:servicePrincipalKey
                #       $env:ARM_TENANT_ID=$env:tenantId
                #       $env:ARM_SUBSCRIPTION_ID="$(azure_subscription_id)"
                #       cd $(Pipeline.Workspace)\drop_infra\environments\dev
                #       terraform init
                #       terraform apply -no-color -auto-approve